#!/bin/bash
# Vercel build script - injects environment variables at build time

echo "🔧 Injecting environment variables..."

# Create env-config.js with API keys from Vercel environment variables
cat > env-config.js << EOF
// Auto-generated by Vercel build
// DO NOT edit this file manually - it's generated at build time
window.ENV = {
    YOUTUBE_API_KEY: '${YOUTUBE_API_KEY:-}',
    FIREBASE_API_KEY: '${FIREBASE_API_KEY:-}',
    FIREBASE_AUTH_DOMAIN: '${FIREBASE_AUTH_DOMAIN:-}',
    FIREBASE_PROJECT_ID: '${FIREBASE_PROJECT_ID:-}',
    FIREBASE_STORAGE_BUCKET: '${FIREBASE_STORAGE_BUCKET:-}',
    FIREBASE_MESSAGING_SENDER_ID: '${FIREBASE_MESSAGING_SENDER_ID:-}',
    FIREBASE_APP_ID: '${FIREBASE_APP_ID:-}'
};
EOF

echo "✅ Environment variables injected successfully"
echo "📦 Build complete - static files ready for deployment"
